[package]
name = "first-go-at-rust"
version = "0.1.0"
authors = ["Bobby <bobbytreacy9\n@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.8.3"
select = "0.5.0"
